# Use the official Node.js image as base
FROM node:14

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy Vue files
COPY . .

# Expose port
EXPOSE 8080

# Run Vue
CMD ["npm", "run", "watch"]