version: "3.7"

services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=9000"]

  vue:
    build:
      context: ./
      dockerfile: Dockerfile.node
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - laravel

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
